blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from blog.views import DetailView, UpdateView, DeleteView, IndexView
app_name = 'blog' #ceci est pour indiquer que tt les noms des url ( details, comment..) appartiennent à l'app blog

urlpatterns = [
    # this section contains the different url in /blog/
    # /blog/
    url(r'^$',views.IndexView, name = 'index'),
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
    url(r'^login/$',  views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    
    url(r'^(?P<username>\w+)/$',  views.Profil, name = 'profil'),
    url(r'^(?P<username>\w+)/edit/$', views.update_profile, name='edit_profile'),
    #/blog/post_id/
    url(r'^detail/(?P<pk>\d+)/$', views.DetailView, name = 'detail'),

    url(r'^post/add/$', views.post_new, name = 'creat' ),
   
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^post/(?P<pk>\d+)/$', views.post_edit , name = 'update'),
    url(r'^comment/(?P<pk>\w+)/remove/$', views.CommentDeleteView.as_view(), name='comment_remove'),
    url(r'^post/(?P<pk>\w+)/delete/$', DeleteView.as_view(), name = 'delete'),

    
    ]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse 
from django.contrib.auth.models import Permission, User
from tinymce.models import HTMLField
from tinymce import models as tinymce_models 
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.FileField(blank=True)
    cover = models.FileField(blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.TextField(max_length=200, blank=True)
    bd = models.FileField(blank=True, null=True) 
    job = models.FileField(blank=True)

    def get_queryset(self):
        user = User.objects.get(username=self.kwargs['username'])
        return self.model.objects(user=user.id)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile(user=instance)
        profile.save()

post_save.connect(create_user_profile, sender=User)


class Post(models.Model):
    user = models.ForeignKey(User, null=True)
    title = models.CharField(max_length=200)
    image = models.CharField(max_length=1000, blank=True)
    #slug = models.SlugField(max_length=255, null=True, blank=True) 
    text = tinymce_models.HTMLField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def __str__(self):
        return self.user
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    #after creating new post redirect to detail page with a primary key 'self.pk'    
    def get_absolute_url (self):
        return reverse('blog:index')
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', null=True,related_name='comments')
    user = models.ForeignKey(User, max_length=200, blank=True, null=True)
    textc = models.CharField(null=True,max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.textc

blog/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Post, Profile, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from tinymce.widgets import TinyMCE


class PostForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(widget=TinyMCE(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ('title', 'text','image') 




class UserForm(forms.ModelForm):
    #TODO: pwd with miniscule, maj, lettres et chiffres
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['password'].required = False
        self.fields['password2'].required = False


    def clean(self):
        super(UserForm, self).clean()
        data = self.cleaned_data
        if data["password"] != data["password2"]:
            raise forms.ValidationError({'password': ["Passwords must be the same."]})
        elif len(data["password"]) <6:
            raise forms.ValidationError({'password': ["password must be at least 6 characters"]})
        return data


    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
        'placeholder': 'Confirm your password'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
        'placeholder': 'Your password'}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Your username'}), 
        max_length=30,
        required=True )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Your email'}),
        required=True,
        label= 'Your Email',

        max_length=75 )

    class Meta:
        model = User
        fields = ['username', 'email', 'password','password2']



class ProfileForm(forms.ModelForm):
    bio = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':
        'Like #movies #kittens #travel #teacher #newyork'}), 
        max_length=300)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':
        'World'}), required=False)
    bd = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':
        'University'}), required=False)
    job = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':
        'Like #developer #administrator'}), required=False)
    class Meta:
        model = Profile
        fields = ('bio','location','avatar','cover','bd','job')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('textc',)

blog/views.py
from .models import Post, Comment
from django.views import generic
from django.views.generic import View, ListView, UpdateView, DeleteView 
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponse, Http404 
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect 
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, PostForm, ProfileForm, CommentForm  
from django.contrib import messages 
from django.utils import timezone 
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView


def Profil(request, username):
	if request.user.is_authenticated():
		base_template_name = 'blog/base.html'
	else:
		base_template_name = 'blog/visitor.html'

	user = User.objects.get(username= username)

	logged_in_user_posts = Post.objects.filter(user=user)
	context = {'base_template_name':base_template_name}
	return render(request, 'blog/profil.html',
	{'user':user, 'posts':logged_in_user_posts,'base_template_name':base_template_name })


		
def update_profile(request, username):
	if request.method == 'POST':
		profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
		if profile_form.is_valid():
			profile_form.save()
			messages.success(request, ('Your profile was successfully updated!'))
			return redirect('blog:index')
		else:
			messages.error(request, ('Please correct the error below.'))
	else:
		profile_form = ProfileForm(instance=request.user.profile)
	return render(request, 'blog/edit_profile.html', {
		'profile_form': profile_form })


def IndexView(request):
	if request.user.is_authenticated():
		base_template_name = 'blog/base.html'
	else:
		base_template_name = 'blog/visitor.html'
	posts = Post.objects.all().order_by('-published_date')
	return render(request, 'blog/index.html', {'posts':posts,'base_template_name':base_template_name})

def add_comment_to_post(request, pk):
	if request.user.is_authenticated():
		base_template_name = 'blog/base.html'
	else:
		base_template_name = 'blog/visitor.html'
	post = get_object_or_404(Post, pk=pk)
	form = CommentForm(request.POST or None)
	if form.is_valid():
		comment = form.save(commit=False)
		comment.user = request.user
		comment.post = post
		comment.save()
		return redirect('blog:index')
	return render(request, 'blog/index.html', {'post':post,'form': form,
	'base_template_name':base_template_name})


def DetailView(request, pk):
	if request.user.is_authenticated():
		base_template_name = 'blog/base.html'
	else:
		base_template_name = 'blog/visitor.html'
	post = get_object_or_404(Post, pk=pk)
	form = CommentForm(request.POST or None)
	if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:detail', pk=pk)
	return render(request,'blog/detail.html',{'post':post,'form':form,
	'base_template_name':base_template_name})

def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.published_date = timezone.now()
			post.save()
			return HttpResponseRedirect(post.get_absolute_url())
	else:
		form = PostForm()
	return render(request, 'blog/post_form.html', {'form': form})
	
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.published_date = timezone.now()
			post.save()
			return HttpResponseRedirect(post.get_absolute_url())
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_form.html', {'form': form}) 
	

class DeleteView(generic.DeleteView):
	model = Post
	success_url = reverse_lazy('blog:index')


def comment_approve(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	comment.approve()
	return redirect('blog:index', pk=comment.post.pk)


class CommentDeleteView(generic.DeleteView):
	model = Comment
	success_url = reverse_lazy('blog:index')


class UserFormView(View):
	form_class = UserForm
	template_name = 'blog/registration.html'

	#Display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	#process from data
	
	def post(self, request):
		form = self.form_class(request.POST)
	
		if form.is_valid():

			user = form.save(commit=False)

			#cleaned data

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# returns user objects if credentials are correct
			user = authenticate(username=username, password= password)
			messages.add_message(request, messages.SUCCESS, 'Your account were successfully created.')
			
			if user is not None:

				if user.is_active:
					login(request, user)
					posts = Post.objects.all()
					base_template_name = 'blog/base.html'
					model = Post
					return render(request, 'blog/index.html',{'posts':posts,'base_template_name':base_template_name}) 
		return render (request, self.template_name, {'form': form})



def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				base_template_name = 'blog/base.html'
				posts = Post.objects.all()
				return render(request, 'blog/index.html', {'posts':posts,'base_template_name':base_template_name})
			else:
				return render(request, 'blog/login.html', {'error_message': 'Your account has been disabled'})
		else:
			return render(request, 'blog/login.html', {'error_message': 'Invalid login'})
	return render(request, 'blog/login.html')

def logout_user(request):
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		"form": form,
	}
	return render(request, 'blog/login.html', context)

#render: conbine un gabarit donné avec un dictionnaire contexte donné
#et renvoie un objet HttpResponse avec le texte résultant. 
#redirect: Renvoie une réponse HttpResponseRedirect à l’URL soit en lui passant
 #un objet ( getabsoluteurl) ou en lui passant un vue ( reverse)

blog/templates/blog/add_comment_to_post.html
    <h1>New comment</h1>
    <form enctype="multipart/form-data" method="post" class="post-form">{% csrf_token %}
        {{ form.textc }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>

    {% block title %}Aabber{% endblock %}</title>
    {% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}">{% endblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="{% static 'blog/js/tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        selector: "textarea",
        menubar: true,
        width: '100%',
        height: 200,
        resize: true,
        plugins: [
             "code advlist autolink link image lists charmap print preview hr pagebreak spellchecker",
             "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
             "save table contextmenu directionality emoticons template paste "
        ],
        toolbar: "code | undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor|  pastetext | fontselect | fontsizeselect | preview ", 
        // ===========================================
        // SET RELATIVE_URLS to FALSE (This is required for images to display properly)
        // ===========================================
        relative_urls: false
     }); 
    </script>
</script>
</head>
<body>
<nav class="navbar-default" style=" background:#41a6dc;z-index:700;
    top: 0; 
    width: 100%; position:fixed; height:50px;">
    <div class="container-fluid" >

        <!-- Header -->
        <div class="navbar-header " >
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img src="{% static 'blog/letter.png' %}" class="img-rounded" alt ="logo" style="height: 50px; -webkit-filter:opacity(50%); filter: invert(100%);">
             <a href="{% url 'blog:index' %}" style="color:white;" >
            <button class="btn btn-primary navbar-btn" style="margin-left:40px; width: 80px;"
             aria-hidden="true" >Blog </button></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse "  id="topNavBar">
            <div class="nav navbar-nav">
                <a href="{% url 'blog:creat' %}"> <button class="btn navbar-btn btn-success" aria-hidden="true" style="color:white;">
                 <span class="glyphicon glyphicon-plus"></span> Add Post</button></a>
            </div>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'blog:index' %}">
                <div class="form-group">
                    <input class="form-control" style="margin-left:100px;" name="q" value="{{ request.GET.q }}" placeholder="Search..."/>
                </div>
            </form>
                <div class="nav navbar-nav navbar-right">
                    <a href="{% url 'blog:logout' %}?next={% url 'blog:login' %}" style="color:white;" >
            <button class="btn btn-success navbar-btn" aria-hidden="true" >
            <span class="glyphicon glyphicon-log-in"></span>
            Log Out</button></a>
                </div>
             <div class="nav navbar-nav navbar-right">
                {% if posts %}
             {% for post in posts %}
                 <a href="{% url 'blog:profil' post.pk %}" style="color:white;" > {%endfor%} {%endif%}
            <button class=" btn navbar-btn btn-success" aria-hidden="true" >
                <span class="user-avatar pull-left">
                                        {% if request.user.profile.avatar %}
                                        <img src="{{ request.user.profile.avatar.url }}" title="John Doe" alt="John Doe" width="30px" height="30px">
                                        {%else%}
                                        <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuLHkpwz9uatkkrzR6FvSyO-AbKAPqTwu8pHrUx2BAtYBjpDCS-Q" title="John Doe" alt="John Doe" width="30px" height="25px">
                                        {%endif%}
                                    </span>&nbsp{{request.user.username}}</button></a>
                </div>
            
        </div>

    </div>
</nav>

{% block body %}

{% endblock %}
</body>
</html>

blog/templates/blog/index.html
{% extends base_template_name %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}">
<script src="js/jquery.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

{% block body %}

<style type="text/css">
    body { background-color:#e6ffff; }


.card {
      padding-top: 10px;
    
    background-color: rgba(214, 224, 226, 0.2);
    border-top-width: 0;
    border-bottom-width: 2px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}


.card .card-heading.simple {
    font-size: 10px;
    font-weight: 300;
    color: #777;
    border-bottom: 1px solid #e5e5e5;
}

.card .card-heading.image img {
    display: inline-block;
    width: 100%;
    height: 100px;
    vertical-align: top;
    border: 0;
    -webkit-border-radius: 50%;
    -moz-border-radius: 50%;
    border-radius: 50%;
}

.card.hovercard .cardheader {

    background-size: cover;
    height: 135px;
}

.card.hovercard .avatar {
    position: relative;
    top: -50px;
    margin-bottom: -50px;
}


.card.hovercard .avatar img {
    width: 100px;
    height: 100px;
    max-width: 100px;
    max-height: 100px;
    -webkit-border-radius: 70%;
    -moz-border-radius: 70%;
    border-radius: 70%;
    border: 5px solid rgba(255,255,255,0.5);
}

.card.hovercard .info {
    padding: 4px 8px 10px;
}

.card.hovercard .info .title {
    margin-bottom: 4px;
    font-size: 24px;
    line-height: 1;
    color: #262626;
    vertical-align: middle;
}

.card.hovercard .info .desc {
    overflow: hidden;
    font-size: 12px;
    line-height: 20px;
    color: #737373;
    text-overflow: ellipsis;
}

.card.hovercard .bottom {
    padding: 0 20px;
    margin-bottom: 17px;
}
#div2 {
  text-overflow: ellipsis;
  word-wrap: break-word;
  overflow: hidden;
  max-height: 6em;
  line-height: 2em;
  padding-left: 10px;
  margin-top: -30px;
  text-align: justify;

}
#com {
  word-wrap: break-word;
  overflow: hidden;
  max-height: 6em;
  line-height: 2em;
  margin-top: -30px;
  text-align: justify;
  padding-left: 70px;
  margin-bottom:20px;

}
#h2 {
    padding-left:15px;
}



</style>
<div class="container" >

<div class="row " style="padding-top:60px;">
{% if user.is_authenticated %}
<div class="col-md-3">

            <div class="card hovercard" style="text-align:center;" >
            {%if user.profile.cover %}
                <div class="cardheader" style="background:url({{user.profile.cover.url}}) no-repeat center center ; height:200px;
                width:100%; background-size: cover;">

                </div>
                {%else%}
                 <div class="cardheader" style="background:url(http://fredeextensions.gettimely.com/images/default-cover-image.jpg) no-repeat center center ; height:200px;
                    width:100%; background-size: cover;">  </div>{%endif%}
                <div class="avatar">
                {% if user.profile.avatar %}
                    <img alt="" src="{{user.profile.avatar.url}}">
                {%else%}
                    <img alt="" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuLHkpwz9uatkkrzR6FvSyO-AbKAPqTwu8pHrUx2BAtYBjpDCS-Q"> {%endif%}
                </div>
                <div class="info">
                    <div class="title">
                        <a href="{% url 'blog:profil' user.username %}">{{user.username}}</a>
                    </div>
                    {% if not user.profile.bio%}
                    <div class="desc" style="font-family:serif;">Introduce yourself</div> {%else%}
                    <div style="font-family:serif;">{{ user.profile.bio|safe }}</div> {%endif%}
                </div>
                
                <div class="bottom">
                            <h4 style="color:#636c72;">Lives in</h4>
                            {% if not user.profile.location %}
                            <p>-</p>{%else%}
                            <p style="font-family:serif;">{{user.profile.location|safe}}</p>{%endif%}
                            
                            <h4 style="color:#636c72;">Studied</h4>
                            {% if not user.profile.bd %}
                            <p>-</p>{%else%}
                            <p style="font-family:serif;">{{user.profile.bd}}</p>{%endif%} 
                            <h4 style="color:#636c72;">Job</h4>
                            {% if not user.profile.job %}
                            <p>-</p>{%else%}
                            <p style="font-family:serif;">{{user.profile.job}}</p>{%endif%} <hr>
                            
                </div>
            </div>

        </div>{%else%}
        <div class="col-md-2"></div>
        {%endif%}

<div class="col-md-7" style="padding-top:10px;">
{% if not user.is_authenticated %}
<div class="panel panel-default">
    <div class="panel-body"> 
    <p style="font-size:20px;color:#66757f;font-family:serief;">New to the website? Sign up now to get your own personalized timeline!</p>
                </div></div>
{%endif%}
           {% if posts %}
             {% for post in posts %}
            <!-- Simple post content example. -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">{% if post.user.profile.avatar %}
                        <a href="#">
                            <img class="media-object img-circle" src="{{post.user.profile.avatar.url}}" width="60px" height="60px" style="margin-right:8px; margin-top:-5px;">
                        </a>
                        {%else%}
                        <a href="#">
                            <img class="media-object img-circle" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuLHkpwz9uatkkrzR6FvSyO-AbKAPqTwu8pHrUx2BAtYBjpDCS-Q" width="50px" height="50px" style="margin-right:8px; margin-top:-5px;">
                        </a>
                            {%endif%}

                    </div>
                    <h4><a href="" style="text-decoration:none;"><strong>
                    <a href="{% url 'blog:profil' post.user.username %}">{{ post.user }}</a></strong></a> – <small><small><a href="{% url 'blog:detail' post.pk %}" style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i>{% if post.published_date %}
                                    {{ post.published_date }}</a>
                              
                            {% endif %}</i></a></small></small></h4>
                    <hr>
                                   
                    <div class="post-content">
                    {% if post.image %}
                    <img src="{{post.image}}" style="float:left;height:140px;padding-right:10px; width:178px;"  alt ="logo">
                    {%endif%}
                        <h2 style="color:grey;"> {{ post.title }} </h2><hr>
                    
        <div id="div2">
        {{ post.text|safe}}</div>
                        <div><a href="{% url 'blog:detail' post.pk %}" class="read-url" style="color:#09c; margin-left:500px;">
                        Read More »</a></div>                 
                    </div>
                    
                    <hr>
                    {% if user.is_authenticated %}
                    <div>
                        <div class="pull-right btn-group-xs">
                            {%if post.user == user %}
                            <a href="{% url 'blog:update' post.pk %}"  class="btn btn-default btn-xs">
                            
                            <span class="glyphicon glyphicon-pencil"></span>
                            
                             Edit</a>
                            <form action="{% url 'blog:delete' post.id %}" method="post" style="display: inline;">
                                                            {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{ post.id }}" />
                            <button type="submit" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-trash"></span>
                             Delete </button> </form> {%else%}
                             <a href="#"  class="btn btn-default btn-xs">
                            
                            <span class="glyphicon glyphicon-share"></span>
                            
                             Share</a>
                             <a href="#"  class="btn btn-default btn-xs">
                            
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            
                             Like</a> {%endif%}
                            <a href="#" class="btn btn-default btn-xs">
                          
                            <span class="glyphicon glyphicon-comment"></span> Comment</a>
                        </div>
                        <br>
                    </div>
                    {%endif%}
                    <hr>
                    <div class="media">
                    {% if not user.is_authenticated %}
                    <h4><a href="{% url 'blog:register' %}"> Sign Up</a> or 
                    <a href="{% url 'blog:login' %}">Log In</a> to comment this post</h4>
                    {%else%}
                        <h4>Leave a Comment:</h4>
                    <form action="{% url 'blog:add_comment_to_post' post.pk %}" method="POST">
                {% csrf_token %}
                <div class="form-group ">
                 <input class="form-control" type="text" id="id_textc" name="textc"></div>
                <div class="form-group ">
                            <button type="submit" id="button" class="btn btn-info btn-large login-button">Comment</button>
                        </div>
                </form>
                        {% for comment in post.comments.all %} 
                          <div class="post-content">
                    {%if user.profile.avatar %}
                    <img style="margin-left:30px;;margin-bottom:20px;border-radius:50%;width:50px;heigth:50px;"
   src="{{comment.user.profile.avatar.url}}"  alt ="logo">{%else%}
    <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuLHkpwz9uatkkrzR6FvSyO-AbKAPqTwu8pHrUx2BAtYBjpDCS-Q" title="John Doe" alt="John Doe" style="margin-bottom:-25px;border-radius:50%;width:60px;heigth:60px;">
                    {%endif%}
                        
           <strong style="color:#337ab7;">{{comment.user}}</strong>

            {{ comment.textc|safe }}</div>
            {% if comment.user == user %}
     <div class="pull-right" style="margin-right:15px;">
      <form action="{% url 'blog:comment_remove' comment.id %}" method="post" style="display: inline;">
                                                            {% csrf_token %}
                            <input type="hidden" name="comment_id" value="{{ comment.id }}" />
                            <button type="submit" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-trash"></span>
                             Delete </button> </form></div>{%endif%}


                            {% endfor %}
                        
                            
                        {%endif%}
                    </div>
                </div>
            </div> {%endfor%} {%endif%}
            <!-- Reshare Example -->   
         
    </div>
</div>
</div>

    
    {% endblock %}
    